name: "postgres16"
services:
  database:
    container_name: postgres16
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
volumes:
  postgres_data: